# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            The Q-Immuno Lab
tagline:          'Quantitative Immunology @ UCL'
description:      'PI: Andreas Tiffeau-Mayer | UCL'
url:              http://qimmuno.com/
baseurl:          /

author:
  name:           'Andreas Tiffeau-Mayer'
  url:            https://twitter.com/andimscience

