# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Andreas Mayer
tagline:          ''
description:      'PhD student in theoretical biophysics at École Normale Supérieure '
url:              http://andim.github.io/
baseurl:          /

author:
  name:           'Andreas Mayer'
  url:            https://twitter.com/andisspam

