# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Andreas Mayer
tagline:          ''
description:      'Physics PhD student'
url:              http://andim.github.io/
baseurl:          /

author:
  name:           'Andreas Mayer'
  url:            https://twitter.com/andisspam

paginate:         5

github:
  repo:           https://github.com/andim/andim.github.io
