# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            The QImmunoLab
tagline:          'Quantitative Immunology Lab @ UCL'
description:      'Led by Andreas Mayer | UCL'
url:              http://andim.github.io/
baseurl:          /

author:
  name:           'Andreas Mayer'
  url:            https://twitter.com/andimscience

