# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Andreas Mayer
tagline:          ''
description:      'PhD student interested in quantitative descriptions of biological systems working in Paris at LPT-ENS'
url:              http://andim.github.io/
baseurl:          /

author:
  name:           'Andreas Mayer'
  url:            https://twitter.com/andisspam

