# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            QImmunoLab @ UCL
tagline:          'Quantitative Immunology @ UCL'
description:      'Group Leader: Andreas Mayer'
url:              http://andim.github.io/
baseurl:          /

author:
  name:           'Andreas Mayer'
  url:            https://twitter.com/andimscience

