# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Andreas Mayer
tagline:          'Quantitative Immunology @ UCL'
description:      'Lecturer at University College London'
url:              http://andim.github.io/
baseurl:          /

author:
  name:           'Andreas Mayer'
  url:            https://twitter.com/andimscience

